server:
  port: 8086

spring:
  application:
    name: tms-service
  datasource:
    url: jdbc:postgresql://localhost:5432/erp_db
    username: erp_user
    password: erp_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
